development:
  adapter: postgresql
  encoding: unicode
  database: gimmemylinks_development
  pool: 5
  username: postgres
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: gimmemylinks_test
  pool: 5
  username: postgres
  password: password1